package org.example.math;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-07-30T14:17:16.018-04:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "MathService", 
                  wsdlLocation = "file:/Users/poornimarajendhran/workspace/github/spring-webservices-soapintegration/implementations/soap-integration/src/main/resources/wsdl/sample.wsdl",
                  targetNamespace = "http://example.org/math") 
public class MathService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example.org/math", "MathService");
    public final static QName MathEndpoint = new QName("http://example.org/math", "MathEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/poornimarajendhran/workspace/github/spring-webservices-soapintegration/implementations/soap-integration/src/main/resources/wsdl/sample.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MathService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/poornimarajendhran/workspace/github/spring-webservices-soapintegration/implementations/soap-integration/src/main/resources/wsdl/sample.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MathService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MathService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MathService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MathService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MathService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WsMath
     */
    @WebEndpoint(name = "MathEndpoint")
    public WsMath getMathEndpoint() {
        return super.getPort(MathEndpoint, WsMath.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsMath
     */
    @WebEndpoint(name = "MathEndpoint")
    public WsMath getMathEndpoint(WebServiceFeature... features) {
        return super.getPort(MathEndpoint, WsMath.class, features);
    }

}
